
const A='assets/';
const TYPES={1:{name:'みんなを引っ張る！・エンジンタイプ',short:'エンジンタイプ',img:A+'lion.jpg',core:'自分から動き、チームを前へ進める人',desc:'指示を待つより、自分から一歩目を踏み出せるタイプ。忙しいときや人手が足りないときほど率先して動き、必要なら周りにも声をかけながらチームを前へ進めます。自分が動き出すことで、お店全体のエンジンになれる存在です。',strength:'行動力・積極性・リーダーシップ',scene:'ピークタイム／人手不足／チームを引っ張る場面'},2:{name:'笑顔で盛り上げる！・ムードメーカータイプ',short:'ムードメーカータイプ',img:A+'parrot.jpg',core:'場を明るくする人',desc:'人とのコミュニケーションが得意で、自然とその場を明るくできるタイプ。お客様との会話はもちろん、一緒に働くスタッフにも良い空気を広げます。あなたがいることで、お店の雰囲気がちょっと楽しくなる存在です。',strength:'コミュニケーション力・親しみやすさ・盛り上げ力',scene:'接客／お客様との会話／スタッフ間の雰囲気づくり'},3:{name:'気づかい上手！・ホスピタリティタイプ',short:'ホスピタリティタイプ',img:A+'sloth.png',core:'相手をよく見て、先回りできる人',desc:'相手の様子をよく見ながら「今、何を求めているかな？」と考えられるタイプ。言われてから動くのではなく、小さな変化に気づいて、その人に合った対応ができます。さりげない気遣いで「また来たい」と思わせられる存在です。',strength:'気配り・観察力・相手に合わせる力',scene:'接客／常連対応／細かなサービス'},4:{name:'アクセル全開！・スピードスタータイプ',short:'スピードスタータイプ',img:A+'cheetah.png',core:'忙しいときほど素早く回す人',desc:'仕事が一気に増えても、テンポよくどんどん処理できるタイプ。特にピークタイムでは持ち前の瞬発力を発揮します。忙しさを「大変」だけで終わらせず、スピード感を持って乗り切れる存在です。',strength:'スピード・瞬発力・処理能力',scene:'ピークタイム／注文処理／料理・ドリンク提供'},5:{name:'とことん極める！・プロフェッショナルタイプ',short:'プロフェッショナルタイプ',img:A+'owl.png',core:'仕事の質を追求する人',desc:'ただ仕事を終わらせるのではなく、「もっと上手く、もっと正確に」と自分の技術を磨いていくタイプ。一つひとつ丁寧に覚え、経験を積むほど強みが増していきます。「この仕事なら任せて」と言えるものを作れる存在です。',strength:'丁寧さ・正確さ・技術を磨く力',scene:'調理／盛り付け／ドリンク作り／質の高い接客'},6:{name:'全体まるっと把握！・オーガナイザータイプ',short:'オーガナイザータイプ',img:A+'octopus.png',core:'全体を見て、うまく回す人',desc:'自分の仕事だけでなく、「今、お店全体はどうなっている？」と周囲を見られるタイプ。誰が忙しいか、どこが詰まっているかを把握して、人や仕事の流れを整理します。チーム全体をスムーズに動かす司令塔のような存在です。',strength:'全体把握・判断力・調整力',scene:'ホール全体管理／スタッフ連携／役割・シフト調整'},7:{name:'痒いところに手が届く！・サポータータイプ',short:'サポータータイプ',img:A+'cat.png',core:'周囲を見ながら、そっと支える人',desc:'困っている人や慣れていない人に気づき、自然とフォローに入れるタイプ。自分だけがうまくいくことより、みんなが働きやすい状態を大切にします。チームにいると「助かる！」と思ってもらえる存在です。',strength:'協調性・フォロー力・チームワーク',scene:'新人フォロー／助け合い／チーム仕事'},8:{name:'ひらめきで変える！・イノベータータイプ',short:'イノベータータイプ',img:A+'fox.png',core:'アイデアで、もっと良くする人',desc:'「これ、もっと良いやり方ないかな？」と考えるのが得意なタイプ。今あるやり方にとらわれず、新しいアイデアや改善方法を考えられます。小さな工夫から、お店そのものをより良く変えていける存在です。',strength:'発想力・改善力・新しいことを考える力',scene:'業務改善／メニュー・企画／店舗づくり'}};
const Q=[['暇な時間','店内を見て、他にできる仕事を探す',[1,4],'次の仕事に備えて、少し休憩する',[2,6]],['忙しい時間','目の前の注文をできるだけ早く処理する',[4,1],'全体を見て、どこから処理するか考える',[6,7]],['お客様との会話','こちらから会話をして場を盛り上げる',[2,8],'お客様の様子を見て、必要なときだけ話しかける',[3,5]],['仕事のやり方','まずは決められたやり方を正確に身につける',[5,3],'もっと良いやり方がないか考える',[8,4]],['仲間が忙しそう','まず自分の担当を終わらせる',[4,1],'一度声をかけて、必要なら手伝う',[7,3]],['トラブル発生','まず社員・先輩に報告して、指示をもらう',[7,2],'状況を整理して、自分でできる対応を考える',[8,1]],['接客','自分が本当におすすめしたいものを紹介する',[2,7],'お客様の好みを聞いて、それに合うものを紹介する',[3,5]],['ピークタイム','自分の仕事をできるだけ速く終わらせる',[4,5],'誰がどの仕事をすれば改善するか考える',[6,8]],['新人が入った','まず自分でやってみてもらう',[1,4],'横について、一緒にやりながら教える',[7,2]],['お客様の変化','普段通りに接客する',[5,6],'何か困っていないか少し気にしてみる',[3,2]],['店づくり','自分自身の接客・調理スキルを高めたい',[5,3],'店全体の仕組みや環境を変えたい',[8,6]],['チームの状況','自分が空いている仕事にどんどん入る',[1,7],'一度全体を見て、誰が何をするか整理する',[6,8]]];
const JOBS=[{id:1,name:'カフェ＆ダイニング Shoku',area:'新宿駅 徒歩3分',w:1300,role:'ホール・キッチン',types:[1,3],tags:['#駅チカ','#まかないあり'],scout:true},{id:2,name:'イタリアンバル Shoku',area:'渋谷駅 徒歩4分',w:1400,role:'ホール・バーテンダー',types:[2,4],tags:['#髪色自由','#シフト自由']},{id:3,name:'和食や Shoku',area:'池袋駅 徒歩2分',w:1200,role:'ホール・キッチン',types:[3,7],tags:['#交通費支給','#未経験歓迎']},{id:4,name:'ビストロ Shoku',area:'銀座駅 徒歩6分',w:1450,role:'ホール',types:[5,6],tags:['#高時給','#昇給あり']},{id:5,name:'ROOFTOP BAR Shoku',area:'六本木駅 徒歩5分',w:1500,role:'バーテンダー',types:[2,8],tags:['#ピアスOK','#終電考慮']},{id:6,name:'ベーカリーカフェ Shoku',area:'東京駅 徒歩4分',w:1280,role:'ホール・キッチン',types:[4,7],tags:['#短時間OK','#学生歓迎']}];
let S=JSON.parse(localStorage.getItem('sm_state')||'{}'); Object.assign(S,{scores:S.scores||{},plus2:S.plus2||{},likes:S.likes||[],passed:S.passed||[],applied:S.applied||[],profile:S.profile||{},logged:S.logged||false}); let hist=[];
const app=document.querySelector('#app'); const save=()=>localStorage.setItem('sm_state',JSON.stringify(S)); const toast=t=>{let x=document.createElement('div');x.className='toast';x.textContent=t;document.body.append(x);setTimeout(()=>x.remove(),1600)};
function go(fn,...a){hist.push([fn,a]);fn(...a)} function back(){hist.pop();let p=hist.pop();p?p[0](...p[1]):landing()};
function wrap(c,nav=''){app.innerHTML=`<div class="mobile blob"><div class="content">${c}</div>${nav?bottom(nav):''}</div>`} function bottom(on){return `<div class="nav"><button class="${on==='rec'?'on':''}" onclick="recommend()"><b>⌂</b>オススメ</button><button class="${on==='search'?'on':''}" onclick="searchPage()"><b>⌕</b>探す</button><button class="${on==='likes'?'on':''}" onclick="likesPage()"><b>♡</b>キニナル</button><button class="${on==='me'?'on':''}" onclick="myPage()"><b>♙</b>マイページ</button></div>`}
function top(title){return `<div class="topbar"><button class="back" onclick="back()">‹</button><b>${title}</b><span>🔔</span></div>`}
function landing(){hist=[];wrap(`<div class="hero landing-hero"><div class="sparkfield">✦　✨　✦</div><div class="brand logo-pop">Shoku↔match</div><p class="kicker">飲食特化の仕事マッチング</p><h1>あなたに合う飲食店と、<br><span class="gradient-text">もっと楽しく出会おう。</span></h1><p class="hero-copy">12問の仕事タイプ診断から、あなたらしく働けるお店を見つけます。</p><div class="animal-parade">${Object.values(TYPES).map((t,i)=>`<img src="${t.img}" alt="" style="--i:${i}">`).join('')}</div><button class="btn primary hero-cta" onclick="startDiag()"><span>✨</span> 無料で仕事タイプを診断する</button><button class="btn login-cta" onclick="auth('ログイン')">ログイン</button><p class="micro">初めての方は診断から／登録済みの方はログイン</p><div class="mini-feature"><span>🧠 12問診断</span><span>👀 スワイプ</span><span>✨ スカウト</span></div></div>`) }
function startDiag(){S.q=0;S.scores={};S.plus2={};save();diag()} function diag(){let i=S.q||0;if(i>=12)return result();let q=Q[i];wrap(`${top('仕事タイプ診断')}<div class="progress"><i style="width:${(i+1)/12*100}%"></i></div><p style="text-align:center">${i+1} / 12</p><div class="card" style="text-align:center"><span class="label">Q${i+1}</span><h2>${q[0]}</h2></div><div class="row"><button class="choice" onclick="answer(${q[2][0]},${q[2][1]})">A<br><br>${q[1]}</button><button class="choice" onclick="answer(${q[4][0]},${q[4][1]})">B<br><br>${q[3]}</button></div><p class="muted" style="text-align:center;margin-top:30px">直感で選んでOK ✨</p>`)}
function answer(x,y){S.scores[x]=(S.scores[x]||0)+2;S.scores[y]=(S.scores[y]||0)+1;S.plus2[x]=(S.plus2[x]||0)+1;S.q++;save();diag()}
function calc(){let r=[1,2,3,4,5,6,7,8].sort((a,b)=>(S.scores[b]||0)-(S.scores[a]||0)||(S.plus2[b]||0)-(S.plus2[a]||0)||a-b);S.main=r[0];S.sub=r[1];save()}
function result(){calc();let m=TYPES[S.main],s=TYPES[S.sub];wrap(`${top('診断結果')}<div style="text-align:center"><span class="spark">✦ ✨ ✦</span><p><b>あなたの仕事タイプは…</b></p><span class="label">MAIN TYPE</span><br><img class="animal" src="${m.img}"><h1 class="title" style="color:var(--o)">${m.name}</h1><b>${m.core}</b><p class="muted">${m.desc}</p></div><div class="card"><b>こんな場面で活躍 ✨</b><p>${m.scene}</p><b>あなたの強み</b><p>${m.strength}</p></div><div class="card" style="background:#e9fbff"><span class="label sub">SUB TYPE</span><div class="row" style="align-items:center"><img src="${s.img}" style="width:90px;height:90px;object-fit:contain"><div><small>あなたにはこんな一面も</small><h3>${s.name}</h3><p>${s.core}</p></div></div></div><button class="btn primary" style="width:100%" onclick="guest3()">あなたに合うお店を見る ✨</button>`)}
function match(j){return S.main&&j.types.some(x=>x===S.main||x===S.sub)}
function guest3(){S.guestIndex=0;let a=[...JOBS].sort((x,y)=>(match(y)?1:0)-(match(x)?1:0));showSwipe(a.slice(0,3),true)}
function recommend(){let arr=JOBS.filter(j=>!S.likes.includes(j.id)&&!S.passed.includes(j.id));if(!arr.length){wrap(`${top('オススメ')}<div class="hero"><h1>ひと通りチェックしました！👀</h1><p>気になるお店は見つかりましたか？<br>もう一度お店を見返してみよう！</p><button class="btn primary" onclick="S.passed=[];save();recommend()">お店を探そう！</button></div>`, 'rec');return} showSwipe(arr,false)}
function showSwipe(arr,guest){let idx=guest?(S.guestIndex||0):0;if(idx>=arr.length){if(guest)return auth('もっと見るには無料会員登録');return recommend()}let j=arr[idx];wrap(`${top(guest?'あなたにおすすめ':'オススメ')}<p style="color:var(--o);font-weight:1000">✨ あなたにおすすめのお店</p>${j.scout&&S.logged?`<div class="notice gold">✨スカウトが届きました！✨<br>${j.name}からあなたにスカウトが届いています</div>`:''}<div class="card job-card" id="swipeCard" onclick="jobDetail(${j.id})"><div class="job-photo"><div>${match(j)?'<span class="tag">✨アナタと相性抜群！</span>':''}<h2>${j.name}</h2><div>${j.area}</div></div></div><div class="job-body"><div>${j.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><div class="price">時給 ${j.w.toLocaleString()}円〜</div><p>🍽 ${j.role}</p></div></div><div class="swipe-actions"><button class="round" onclick="event.stopPropagation();act(${j.id},'pass',${guest})">✕<br>見送る</button><button class="round like" onclick="event.stopPropagation();act(${j.id},'like',${guest})">♥<br>キニナル</button></div><p class="muted" style="text-align:center">← 見送る　　右へスワイプでキニナル →</p>`, 'rec');bindSwipe(j.id,guest)}
function bindSwipe(id,guest){let c=document.querySelector('#swipeCard'),x=0,start=0;if(!c)return;c.addEventListener('touchstart',e=>start=e.touches[0].clientX);c.addEventListener('touchmove',e=>{x=e.touches[0].clientX-start;c.style.transform=`translateX(${x}px) rotate(${x/25}deg)`});c.addEventListener('touchend',()=>{if(x>85)act(id,'like',guest);else if(x<-85)act(id,'pass',guest);else c.style.transform='';x=0})}
function act(id,type,guest){let card=document.querySelector('#swipeCard');if(card){card.classList.add(type==='like'?'fly-right':'fly-left')}if(type==='like'){if(!S.logged&&S.likes.length>=3)return auth('キニナルをもっと保存するには会員登録');if(!S.likes.includes(id))S.likes.push(id);toast('👀 キニナルに追加しました')}else{if(!S.passed.includes(id))S.passed.push(id);toast('見送り履歴に保存しました')}if(guest)S.guestIndex=(S.guestIndex||0)+1;save();guest?showSwipe(JOBS.slice(0,3),true):recommend()}
function auth(head='ログイン・会員登録'){wrap(`${top(head)}<div class="brand" style="text-align:center;margin:22px">Shoku↔match ✨</div><div class="tabs"><button class="on">ログイン</button><button>新規登録</button></div><div class="card"><input class="input" placeholder="メールアドレス"><input class="input" type="password" placeholder="パスワード（半角英数8文字以上）"><button class="btn primary" style="width:100%" onclick="login()">ログイン</button><p class="muted" style="text-align:center">パスワードをお忘れの方はこちら</p></div><div class="card"><b>アカウントをお持ちでない方</b><p>メール認証 → パスワード設定 → 基本プロフィール</p><button class="btn light" style="width:100%" onclick="register()">新規登録（無料）</button></div>`)} function login(){S.logged=true;save();recommend()} function register(){S.logged=true;S.profile={username:'りこ',age:'27',experience:'1年以上',work:'飲食店 アルバイト'};save();toast('メール認証をデモ完了しました');recommend()}
function searchPage(){wrap(`${top('探す')}<h1 class="title">条件を指定して探す 🔍</h1>${['📍 勤務地　駅・エリアを選択','⭐ 最低時給　1,200円以上','🍽 業態　カフェ・ダイニング','▣ 職種　ホール・キッチン','🕘 希望勤務時間　指定なし','▦ 最低シフト　週2日から','💄 身だしなみ　指定なし','🎁 待遇　指定なし','🚲 通勤方法　指定なし','✨ 店舗の雰囲気　指定なし'].map(x=>`<div class="list-item"><b>${x}</b><span style="margin-left:auto">›</span></div>`).join('')}<button class="btn primary" style="width:100%;margin-top:20px" onclick="searchResults()">この条件で検索する</button>`, 'search')}
function searchResults(){wrap(`${top('検索結果')}<div class="row"><h2>検索結果 <b>56件</b></h2><button class="btn light">おすすめ順</button></div>${JOBS.map(j=>`<div class="card" onclick="jobDetail(${j.id})"><div class="thumb" style="width:100%;height:140px"></div>${match(j)?'<span class="tag">✨相性抜群</span>':''}<h3>${j.name} ${S.likes.includes(j.id)?'♥':''}</h3><p>${j.area}</p><b class="price" style="font-size:19px">時給 ${j.w.toLocaleString()}円〜</b><p>${j.role}</p></div>`).join('')}<div class="notice"><b>条件にぴったりのお店がない場合</b><br>条件が近いお店を表示し、「希望時給より−50円」「希望時間と1時間差」のように違いをお知らせします。</div>`, 'search')}
function jobDetail(id){let j=JOBS.find(x=>x.id===id);wrap(`<div class="detail-hero"><button class="back" onclick="back()">‹</button></div><div class="content" style="padding-top:0"><div>${j.tags.map(x=>`<span class="tag">${x}</span>`).join('')}</div><h1>${j.name}</h1><p>${j.area}</p><div class="price">時給 ${j.w.toLocaleString()}円〜 <small style="font-size:12px;color:#7b7067">（研修時給1,200円）</small></div><p>🍽 ${j.role}</p>${j.scout?'<div class="notice gold">✨スカウトが届いたお店</div>':''}${['募集条件','仕事内容','お店について','待遇・身だしなみ','あなたに合う理由','勤務地・アクセス'].map((x,i)=>`<div class="card"><h3>${x}</h3><p>${i===0?'勤務時間 10:00〜23:00／週2日・1日4時間〜':i===1?'接客、オーダー、料理・ドリンク提供など。役割ごとの仕事内容を掲載します。':i===2?'スタッフ同士で声をかけ合う、明るく活気のあるお店です。':i===3?'まかないあり・交通費支給・髪色自由・ネイルOK':i===4?(match(j)?`このお店が求めている「${TYPES[j.types[0]].short}」と、あなたの診断結果がマッチしています。`:'お店が求める仕事タイプを確認できます。'):'東京都内／最寄駅から徒歩。電車・自転車通勤可。店舗ページを見る'}</p></div>`).join('')}</div><div class="sticky-actions"><button class="btn light" onclick="act(${id},'like',false)">♡ キニナル</button><button class="btn primary" onclick="applyPage(${id})">応募する</button></div>${bottom('')}`)}
function likesPage(){let arr=JOBS.filter(j=>S.likes.includes(j.id));wrap(`${top('キニナル')}<div class="tabs"><button class="on">すべて (${arr.length})</button><button>スカウト</button></div>${arr.length?arr.map(j=>`<div class="list-item" onclick="jobDetail(${j.id})"><div class="thumb"></div><div><b>${j.scout?'✨スカウトが届いたお店<br>':''}${j.name}</b><p>${j.area}<br><b style="color:var(--o)">時給 ${j.w.toLocaleString()}円〜</b></p></div><span style="margin-left:auto;color:red">♥</span></div>`).join(''):'<div class="hero"><h2>まだキニナルはありません</h2></div>'}<button class="btn light" style="width:100%;margin-top:20px" onclick="passedPage()">見送り履歴を見る</button>`, 'likes')}
function passedPage(){let arr=JOBS.filter(j=>S.passed.includes(j.id));wrap(`${top('見送り履歴')}${arr.map(j=>`<div class="list-item"><div class="thumb"></div><div><b>${j.name}</b><p>${j.scout?'元スカウト求人<br>':''}${j.area}</p></div><button class="btn light" onclick="S.passed=S.passed.filter(x=>x!==${j.id});S.likes.push(${j.id});save();passedPage()">👀</button></div>`).join('')||'<p>見送り履歴はありません。</p>'}`)}
function applyPage(id){if(S.applied.includes(id))return toast('この求人には再応募できません');let j=JOBS.find(x=>x.id===id);wrap(`${top('応募する')}<div class="steps"><i class="on"></i><i></i><i></i></div><h2>応募情報の入力</h2>${['本名','フリガナ','生年月日','電話番号','住所','最寄り駅','現在の職','高校：卒業年／在学中／中退','大学：卒業年／在学中／中退／進学していない'].map(x=>`<input class="input" placeholder="${x}">`).join('')}<button class="btn primary" style="width:100%" onclick="resumePreview(${id})">次へ（履歴書の確認へ）</button>`)}
function resumePreview(id){let j=JOBS.find(x=>x.id===id);wrap(`${top('履歴書の確認')}<div class="notice">応募内容から履歴書を自動作成します<br>ご登録いただいたプロフィール・応募時に入力した情報をもとに、Shoku↔matchが履歴書を自動作成し、応募先企業へ送信します。</div><div class="card"><div style="text-align:right">Shoku↔match 履歴書</div><h2>田中 理子</h2><p>タナカ リコ　1998年12月27日</p><p>住所：東京都板橋区…　最寄駅：池袋駅</p><p>現在の職：飲食店 アルバイト</p><p>学歴：2021年3月 ○○大学 卒業</p><p>飲食経験：カフェ 2年／居酒屋 1年</p><p>資格・スキル：接客、ドリンク作成</p><hr><p><span class="label">MAIN TYPE</span> ${TYPES[S.main||1].short}</p><p><span class="label sub">SUB TYPE</span> ${TYPES[S.sub||2].short}</p><small>※この内容で応募します。顔写真は使用しません。</small></div><button class="btn primary" style="width:100%" onclick="submitApply(${id})">この内容で応募する</button>`)}
function submitApply(id){S.applied.push(id);save();wrap(`${top('応募完了')}<div class="hero"><div style="font-size:55px">🎉</div><h1>応募しました！</h1><p>企業が面接へ進める場合、面接候補日が届きます。</p><button class="btn primary" onclick="interviewDates(${id})">デモ：面接候補日を見る</button><button class="btn light" onclick="resumePreview(${id})">送信した履歴書を見る</button></div>`)}
function interviewDates(id){wrap(`${top('面接日程の選択')}<p>企業から面接候補日が届きました。ご都合の良い日時を選択してください。</p>${['9月28日（月）','9月29日（火）','10月1日（水）'].map(d=>`<div class="card"><b>${d}</b><div class="tabs"><button>14:00 - 14:30</button><button class="on" onclick="confirmInterview()">15:00 - 15:30</button><button>16:00 - 16:30</button></div></div>`).join('')}<button class="btn light" style="width:100%">候補が合わない（2〜3候補を送る）</button>`)}
function confirmInterview(){toast('面接日時を確定しました');myPage()}
function myPage(){let m=TYPES[S.main||1],s=TYPES[S.sub||2];wrap(`${top('マイページ')}<div class="card"><div class="row" style="align-items:center"><img src="${m.img}" style="width:80px;height:80px;object-fit:contain"><div><h2>${S.profile.username||'田中 理子'}</h2><p>${S.profile.age||'27'}歳</p><span class="tag">${m.short}</span><span class="tag blue">${s.short}</span></div></div><button class="btn light">プロフィールを編集</button></div>${['📋 応募・選考状況','🗓 面接予定','♡ キニナル一覧','⊗ 見送り履歴','✨ スカウト履歴','💬 メッセージ','🧠 仕事タイプ診断結果','✎ 登録情報の編集','⚙ アカウント・通知設定','？ ヘルプ・お問い合わせ'].map(x=>`<div class="list-item"><b>${x}</b><span style="margin-left:auto">›</span></div>`).join('')}<button class="btn light" style="width:100%;margin-top:18px" onclick="startDiag()">仕事タイプを再診断する</button>`, 'me')}
function employerLogin(mode='home'){
  const signup = mode==='signup';
  const login = mode==='login';
  app.innerHTML=`<div class="biz-entry"><div class="biz-entry-card"><div class="biz-brand">Shoku↔match <span>企業向け</span></div>${mode==='home'?`<h1>飲食店の採用を、もっとシンプルに。</h1><p class="biz-lead">求人掲載・応募者管理・スカウトをひとつの画面で管理できます。</p><button class="btn biz-primary" onclick="employerLogin('signup')">企業アカウントを新規登録</button><button class="btn biz-secondary" onclick="employerLogin('login')">ログイン</button><p class="biz-note">企業・店舗向けの管理サービスです。</p>`:signup?`<button class="biz-back" onclick="employerLogin()">‹ 戻る</button><h1>企業アカウントを新規登録</h1><p class="biz-lead">まずは会社情報と担当者情報を登録します。</p><input class="input" placeholder="会社名"><input class="input" placeholder="担当者名"><input class="input" type="email" placeholder="メールアドレス"><input class="input" type="password" placeholder="パスワード"><button class="btn biz-primary" onclick="employerSignupFlow()">登録して次へ</button><p class="biz-switch">すでにアカウントをお持ちですか？ <button onclick="employerLogin('login')">ログイン</button></p>`:`<button class="biz-back" onclick="employerLogin()">‹ 戻る</button><h1>企業ログイン</h1><input class="input" type="email" placeholder="メールアドレス"><input class="input" type="password" placeholder="パスワード"><button class="btn biz-primary" onclick="employer()">ログイン</button><p class="biz-switch">初めての企業様は <button onclick="employerLogin('signup')">新規登録</button></p>`}</div></div>`;
}
function employerSignupFlow(){
 app.innerHTML=`<div class="biz-entry"><div class="biz-entry-card wide"><div class="biz-brand">Shoku↔match <span>企業向け</span></div><div class="biz-step">STEP 1 / 4</div><h1>企業情報を登録</h1><p class="biz-lead">デモ版では、この先の「店舗情報登録 → 運営審査 → プラン選択 → 利用開始」を確認できます。</p><input class="input" placeholder="会社名"><input class="input" placeholder="所在地"><input class="input" placeholder="担当者名"><button class="btn biz-primary" onclick="employer()">デモ：登録を完了して管理画面へ</button><p class="biz-note">本番では初月無料、2か月目から選択プランで自動更新する想定です。</p></div></div>`
}
const ENAV=['ホーム','店舗・求人管理','応募者管理','人材を探す','スカウト管理','契約・料金','企業設定'];
function employer(page='ホーム'){app.innerHTML=`<div class="desk"><aside class="side"><div class="brand">Shoku↔match</div><p>採用管理</p>${ENAV.map(x=>`<button class="${x===page?'on':''}" onclick="employer('${x}')">${x}</button>`).join('')}<button onclick="landing()">← 求職者サイト</button></aside><main class="main"><div class="desk-mobile-head brand">Shoku↔match 企業向け</div>${empContent(page)}</main></div>`}
function empContent(p){if(p==='ホーム')return `<div class="row"><div><h1>採用ダッシュボード</h1><p>全店舗 ▾</p></div><span>🔔</span></div><div class="grid"><div class="metric">新着応募<br><b>8</b>件</div><div class="metric">日程調整中<br><b>3</b>件</div><div class="metric">本日の面接<br><b>2</b>件</div></div><div class="card"><h2>対応が必要です</h2><div class="notice">選考結果の入力をお忘れではありませんか？ 面接から5日が経過しました。選考が完了している場合は、結果の入力をお願いいたします。</div></div><div class="card"><h2>最近の応募者</h2>${applicants()}</div>`;
if(p==='店舗・求人管理')return `<div class="row"><h1>店舗・求人管理</h1><button class="btn primary" onclick="jobCreate()">＋ 求人を作成</button></div><div class="card"><h2>カフェ＆ダイニング Shoku</h2><p>公開中　ホール・キッチン／時給1,300円〜</p><span class="badge">写真8枚</span> <span class="badge">求めるタイプ 1・3</span><div class="row"><button class="btn light">編集</button><button class="btn light">一時停止</button></div></div>`;
if(p==='応募者管理')return `<h1>応募者管理</h1><div class="tabs"><button class="on">新着</button><button>面接調整中</button><button>面接予定</button><button>選考中</button><button>採用者</button><button>不採用</button></div><div class="card">${applicants()}</div>`;
if(p==='人材を探す')return `<h1>人材を探す 🔍</h1><p>プロフィール完成ユーザーのみ表示。MAIN TYPEで検索できます。</p>${[1,2,3].map((x,i)=>`<div class="card"><div class="row"><img src="${TYPES[x].img}" style="width:70px;height:70px;object-fit:contain"><div><h3>ユーザー${i+1}　${24+i}歳</h3><span class="tag">${TYPES[x].short}</span><span class="tag blue">SUB ${TYPES[x+1].short}</span><p>飲食経験 ${i+1}年／希望：新宿・渋谷／18:00〜23:00</p></div></div><button class="btn primary">この求人でスカウト</button></div>`).join('')}`;
if(p==='スカウト管理')return `<h1>スカウト管理</h1><div class="grid"><div class="metric">今月利用<br><b>2</b> / 5件</div><div class="metric">残り<br><b>3</b>件</div><div class="metric">キニナル反応<br><b>1</b>件</div></div><div class="card"><h2>テンプレート</h2><textarea class="input">プロフィールを拝見し、ぜひ一度お話ししたいと思いスカウトしました。</textarea><div class="row"><button class="btn light">編集</button><button class="btn light">削除</button></div></div>`;
if(p==='契約・料金')return `<h1>契約・料金</h1><div class="card"><h2>現在のプラン</h2><p>1店舗 月額〇円　／　初月無料</p><h3>スカウト追加</h3><p>標準 5件/月</p><p>10件 ＋3,000円　20件 ＋5,000円　無制限 ＋20,000円</p><p class="muted">契約開始日基準で毎月更新。解約は期間末で求人非公開、進行中の選考は管理できます。</p></div>`;
return `<h1>企業設定</h1><div class="card"><h3>会社情報</h3><input class="input" value="株式会社Shoku"><h3>通知</h3><p>☑ 新着応募　☑ 面接日程　☑ 選考結果入力リマインド</p><h3>店舗ページURL（任意）</h3><input class="input" placeholder="公式ホームページもしくはInstagramなど"></div>`}
function applicants(){return `<table><tr><th>応募者</th><th>タイプ</th><th>店舗/職種</th><th>状態</th><th></th></tr><tr><td>りこ / 27歳 / 女性<br>飲食経験3年</td><td><img src="${TYPES[1].img}" style="width:38px;height:38px;object-fit:contain"> ${TYPES[1].short}</td><td>新宿店 / ホール</td><td><span class="badge">応募済み</span></td><td><button class="btn primary" onclick="applicantDetail()">詳細</button></td></tr></table>`}
function applicantDetail(){app.innerHTML=`<div class="desk"><aside class="side"><div class="brand">Shoku↔match</div><button onclick="employer('応募者管理')">← 応募者一覧</button></aside><main class="main"><h1>応募者詳細</h1><div class="card"><div class="row"><img src="${TYPES[1].img}" style="width:100px;height:100px;object-fit:contain"><div><h2>りこ　27歳</h2><span class="tag">MAIN ${TYPES[1].short}</span><span class="tag blue">SUB ${TYPES[2].short}</span></div></div><p>飲食経験3年／現在：飲食店アルバイト／希望エリア：新宿・池袋</p><p>資格・スキル：接客、ドリンク作成</p><p>自己PR：人と話すことが好きです。</p><button class="btn light">履歴書を見る</button><button class="btn light">PDF保存</button><button class="btn light">印刷する</button></div><div class="row"><button class="btn light">見送る</button><button class="btn primary" onclick="empInterview()">面接へ進める</button></div></main></div>`}
function empInterview(){app.innerHTML=`<div class="desk"><aside class="side"><div class="brand">Shoku↔match</div></aside><main class="main"><h1>面接候補日を送る</h1><div class="card"><label>面接時間</label><select class="input"><option>30分</option><option>15分</option><option>45分</option><option>60分</option><option>カスタム</option></select><input class="input" value="9/28 14:00〜17:00"><input class="input" value="9/29 14:00〜17:00"><input class="input" value="10/1 14:00〜17:00"><textarea class="input" placeholder="コメント（任意）"></textarea><button class="btn primary" onclick="toast('面接候補日を送信しました')">候補日を送信</button></div></main></div>`}
function jobCreate(){app.innerHTML=`<div class="desk"><aside class="side"><div class="brand">Shoku↔match</div><button onclick="employer('店舗・求人管理')">← 求人管理</button></aside><main class="main"><h1>求人を作成</h1><div class="steps"><i class="on"></i><i class="on"></i><i></i><i></i><i></i></div><div class="tabs"><button class="on">①基本情報</button><button>②勤務条件</button><button>③特徴・待遇</button><button>④写真</button><button>⑤確認・公開</button></div><div class="card"><h3>① 基本情報</h3><select class="input"><option>カフェ＆ダイニング Shoku</option></select><input class="input" value="カフェ・ダイニング"><p>職種（複数選択）</p><p>☑ ホール　☑ キッチン　□ バーテンダー　□ 洗い場　□ その他</p><textarea class="input" placeholder="職種ごとの仕事内容"></textarea><p>推しポイント（ちょうど2つ）</p><span class="tag">#高時給</span><span class="tag">#まかないあり</span><span class="tag blue">#髪色自由</span><h3>② 勤務条件</h3><input class="input" value="時給 1,300円"><input class="input" value="研修時給 1,200円 / 1ヶ月"><input class="input" value="10:00〜23:00"><input class="input" value="週2日〜 / 1日4時間〜"><h3>③ お店の特徴・待遇</h3><p>☑まかない ☑交通費 ☑髪色自由 ☑ネイルOK</p><p>求める仕事タイプ（1〜3）</p>${[1,3,7].map(x=>`<span class="tag"><img src="${TYPES[x].img}" style="width:22px;height:22px;vertical-align:middle"> ${TYPES[x].short}</span>`).join('')}<h3>④ 写真</h3><div class="notice">3〜8枚必須。制服写真を推奨。AI生成・実態と大きく異なる加工は禁止。</div><h3>⑤ 確認・公開</h3><p>ステータス：下書き → 写真審査中 → 公開中 / 一時停止</p><button class="btn primary">プレビューして公開</button></div></main></div>`}
landing();
