const A='./assets/';
const types={1:{name:'みんなを引っ張る！・エンジンタイプ',img:'lion.jpg',desc:'指示を待つより、自分から一歩目を踏み出せるタイプ。忙しいときや人手が足りないときほど率先して動き、必要なら周りにも声をかけながらチームを前へ進めます。自分が動き出すことで、お店全体のエンジンになれる存在です。',strength:['行動力','積極性','リーダーシップ'],short:'自分から動き、チームを前へ進める人'},2:{name:'笑顔で盛り上げる！・ムードメーカータイプ',img:'parrot.jpg',desc:'人とのコミュニケーションが得意で、自然とその場を明るくできるタイプ。お客様との会話はもちろん、一緒に働くスタッフにも良い空気を広げます。あなたがいることで、お店の雰囲気がちょっと楽しくなる存在です。',strength:['コミュニケーション力','親しみやすさ','盛り上げ力'],short:'場を明るくする人'},3:{name:'気づかい上手！・ホスピタリティタイプ',img:'sloth.png',desc:'相手の様子をよく見ながら「今、何を求めているかな？」と考えられるタイプ。言われてから動くのではなく、小さな変化に気づいて、その人に合った対応ができます。さりげない気遣いで「また来たい」と思わせられる存在です。',strength:['気配り','観察力','相手に合わせる力'],short:'相手をよく見て、先回りできる人'},4:{name:'アクセル全開！・スピードスタータイプ',img:'cheetah.png',desc:'仕事が一気に増えても、テンポよくどんどん処理できるタイプ。特にピークタイムでは持ち前の瞬発力を発揮します。忙しさを「大変」だけで終わらせず、スピード感を持って乗り切れる存在です。',strength:['スピード','瞬発力','処理能力'],short:'忙しいときほど素早く回す人'},5:{name:'とことん極める！・プロフェッショナルタイプ',img:'owl.png',desc:'ただ仕事を終わらせるのではなく、「もっと上手く、もっと正確に」と自分の技術を磨いていくタイプ。一つひとつ丁寧に覚え、経験を積むほど強みが増していきます。「この仕事なら任せて」と言えるものを作れる存在です。',strength:['丁寧さ','正確さ','技術を磨く力'],short:'仕事の質を追求する人'},6:{name:'全体まるっと把握！・オーガナイザータイプ',img:'octopus.png',desc:'自分の仕事だけでなく、「今、お店全体はどうなっている？」と周囲を見られるタイプ。誰が忙しいか、どこが詰まっているかを把握して、人や仕事の流れを整理します。チーム全体をスムーズに動かす司令塔のような存在です。',strength:['全体把握','判断力','調整力'],short:'全体を見て、うまく回す人'},7:{name:'痒いところに手が届く！・サポータータイプ',img:'cat.png',desc:'困っている人や慣れていない人に気づき、自然とフォローに入れるタイプ。自分だけがうまくいくことより、みんなが働きやすい状態を大切にします。チームにいると「助かる！」と思ってもらえる存在です。',strength:['協調性','フォロー力','チームワーク'],short:'周囲を見ながら、そっと支える人'},8:{name:'ひらめきで変える！・イノベータータイプ',img:'fox.png',desc:'「これ、もっと良いやり方ないかな？」と考えるのが得意なタイプ。今あるやり方にとらわれず、新しいアイデアや改善方法を考えられます。小さな工夫から、お店そのものをより良く変えていける存在です。',strength:['発想力','改善力','新しいことを考える力'],short:'アイデアで、もっと良くする人'}};
const qs=[['暇な時間','店内を見て、他にできる仕事を探す','次の仕事に備えて、少し休憩する','1.4','2.6'],['忙しい時間','目の前の注文をできるだけ早く処理する','全体を見て、どこから処理するか考える','4.1','6.7'],['お客様との会話','こちらから会話をして場を盛り上げる','お客様の様子を見て、必要なときだけ話しかける','2.8','3.5'],['仕事のやり方','まずは決められたやり方を正確に身につける','もっと良いやり方がないか考える','5.3','8.4'],['仲間が忙しそう','まず自分の担当を終わらせる','一度声をかけて、必要なら手伝う','4.1','7.3'],['トラブル発生','まず社員・先輩に報告して、指示をもらう','状況を整理して、自分でできる対応を考える','7.2','8.1'],['接客','自分が本当におすすめしたいものを紹介する','お客様の好みを聞いて、それに合うものを紹介する','2.7','3.5'],['ピークタイム','自分の仕事をできるだけ速く終わらせる','誰がどの仕事をすれば改善するか考える','4.5','6.8'],['新人が入った','まず自分でやってみてもらう','横について、一緒にやりながら教える','1.4','7.2'],['お客様の変化','普段通りに接客する','何か困っていないか少し気にしてみる','5.6','3.2'],['店づくり','自分自身の接客・調理スキルを高めたい','店全体の仕組みや環境を変えたい','5.3','8.6'],['チームの状況','自分が空いている仕事にどんどん入る','一度全体を見て、誰が何をするか整理する','1.7','6.8']];
let qi=0,ans=[]; const app=document.getElementById('app');
const shell=x=>`<div class="app">${x}</div>`; const header=(r='')=>`<header class="top"><div class="logo">Shoku<b>↔</b>match</div>${r}</header>`;
function home(){app.innerHTML=shell(header('<span style="font-size:12px;font-weight:800">飲食専門求人</span>')+`<section class="hero"><span class="pill">🍽 飲食業界専門マッチング</span><h1>条件だけじゃない。<br><em>相性で、働こう。</em></h1><p>あなたの性格・働き方から、<br>「本当に合うお店」を見つけます。</p><button class="btn primary" onclick="start()">無料で仕事タイプ診断</button><div class="note">✓ 約2分　✓ 全12問　✓ 登録なし</div></section><section class="section"><div class="eyebrow">WHY SHOKU↔MATCH?</div><h2>飲食の仕事探しを、もっと自分らしく。</h2><div class="feature"><article><i>🧡</i><div><h3>8つの仕事タイプ</h3><p>12問からMAINとSUB、2つのあなたらしさを診断。</p></div></article><article><i>✨</i><div><h3>相性のいいお店がわかる</h3><p>お店が求める仕事タイプと一致すると相性抜群を表示。</p></div></article><article><i>👀</i><div><h3>気になる求人を比較</h3><p>気になるお店を保存して、自分のペースで探せます。</p></div></article></div></section>`)}
window.start=()=>{qi=0;ans=[];question()}; function question(){let q=qs[qi];app.innerHTML=shell(header('<span>仕事タイプ診断</span>')+`<main class="diag"><div class="qtop"><span>QUESTION ${qi+1} / 12</span><span>約2分</span></div><div class="track"><div class="bar" style="width:${(qi+1)/12*100}%"></div></div><section class="qcard"><div class="eyebrow">${q[0]}</div><h2>${q[0]}、あなたに近いのは？</h2><div class="hint">直感で近い方を選んでください</div><button class="answer" onclick="pick('${q[3]}')">A　${q[1]}</button><button class="answer" onclick="pick('${q[4]}')">B　${q[2]}</button></section>${qi?'<button class="back" onclick="prev()">← ひとつ前に戻る</button>':''}</main>`)}
window.pick=s=>{ans[qi]=s;qi++;qi<12?question():finish()};window.prev=()=>{if(qi){qi--;ans=ans.slice(0,qi);question()}};
function finish(){let score={},plus={};for(let i=1;i<=8;i++)score[i]=plus[i]=0;ans.forEach(s=>{let [x,y]=s.split('.').map(Number);score[x]+=2;plus[x]++;score[y]+=1});let rank=[1,2,3,4,5,6,7,8].sort((a,b)=>score[b]-score[a]||plus[b]-plus[a]||a-b);localStorage.setItem('smResult',JSON.stringify({main:rank[0],sub:rank[1]}));result(rank[0],rank[1])}
function result(m,s){let x=types[m],y=types[s];app.innerHTML=shell(header('<span>診断結果</span>')+`<main class="result"><div class="eyebrow">YOUR WORK TYPE</div><p>あなたの仕事タイプは…</p><img class="animal" src="${A+x.img}"><div class="mainbadge">MAIN TYPE</div><h1>${x.name}</h1><p class="desc">${x.desc}</p><div class="chips">${x.strength.map(v=>`<span class="chip">${v}</span>`).join('')}</div><div class="subcard"><img src="${A+y.img}"><div><span class="subbadge">あなたにはこんな一面も・SUB TYPE</span><strong>${y.name}</strong><p>${y.short}</p></div></div><button class="btn primary" onclick="jobs(${m},${s})">あなたに合うお店を見る</button><button class="btn secondary" onclick="start()">もう一度診断する</button></main>`)}
const stores=[
{id:1,name:'Trattoria LUNA',cat:'カジュアルイタリアン',station:'池袋駅 徒歩3分',area:'池袋',wage:1450,role:'ホール',types:[2,3],icon:'🍝',tags:['#まかないあり','#髪色自由'],hours:'10:00〜23:30',shift:'週2日〜 / 1日4時間〜',copy:'会話を楽しみながら働ける、明るくカジュアルなイタリアン。',benefits:['交通費支給','まかないあり','制服貸与','未経験歓迎'],url:''},
{id:2,name:'SUSHI AO',cat:'寿司・和食',station:'六本木駅 徒歩5分',area:'六本木',wage:1600,role:'ホール・キッチン',types:[5,6],icon:'🍣',tags:['#高時給','#昇給あり'],hours:'11:00〜23:00',shift:'週3日〜 / 1日5時間〜',copy:'丁寧な仕事とチーム連携を大切にする寿司店です。',benefits:['交通費支給','昇給あり','制服貸与','経験者歓迎'],url:''},
{id:3,name:'TORICO',cat:'焼鳥・居酒屋',station:'新宿駅 徒歩4分',area:'新宿',wage:1500,role:'ホール',types:[1,4,7],icon:'🍢',tags:['#未経験歓迎','#学生歓迎'],hours:'16:00〜翌1:00',shift:'週2日〜 / 1日4時間〜',copy:'ピークをみんなで乗り切る、活気ある焼鳥店。',benefits:['まかないあり','交通費支給','未経験歓迎','深夜手当'],url:''},
{id:4,name:'CAFÉ BLANC',cat:'カフェ',station:'表参道駅 徒歩4分',area:'表参道',wage:1400,role:'ホール・バリスタ',types:[3,8],icon:'☕',tags:['#駅チカ','#シフト自由'],hours:'8:00〜21:00',shift:'週2日〜 / 1日4時間〜',copy:'小さな気づかいとアイデアを歓迎するカフェ。',benefits:['交通費支給','社員登用あり','シフト相談OK','ネイルOK'],url:''},
{id:5,name:'GINZA 凛',cat:'割烹・日本料理',station:'銀座駅 徒歩2分',area:'銀座',wage:1700,role:'ホール',types:[3,5],icon:'🍱',tags:['#高時給','#駅チカ'],hours:'16:00〜23:00',shift:'週3日〜 / 1日5時間〜',copy:'上質な接客を一つずつ身につけられる落ち着いた割烹。',benefits:['交通費支給','昇給あり','制服貸与','経験者歓迎'],url:''},
{id:6,name:'PIZZA POP',cat:'ピッツェリア',station:'渋谷駅 徒歩6分',area:'渋谷',wage:1480,role:'ホール・キッチン',types:[1,2,4],icon:'🍕',tags:['#髪色自由','#WワークOK'],hours:'11:00〜24:00',shift:'週2日〜 / 1日4時間〜',copy:'元気とスピードを活かせるカジュアルなピッツェリア。',benefits:['まかないあり','髪色自由','WワークOK','昇給あり'],url:''}];
const state={screen:'home',user:JSON.parse(localStorage.getItem('smUser')||'null'),liked:JSON.parse(localStorage.getItem('smLiked')||'[]'),passed:JSON.parse(localStorage.getItem('smPassed')||'[]'),apps:JSON.parse(localStorage.getItem('smApps')||'[]'),scouts:JSON.parse(localStorage.getItem('smScouts')||'[6]'),employer:false};
function save(){localStorage.setItem('smLiked',JSON.stringify(state.liked));localStorage.setItem('smPassed',JSON.stringify(state.passed));localStorage.setItem('smApps',JSON.stringify(state.apps));localStorage.setItem('smUser',JSON.stringify(state.user))}
function res(){return JSON.parse(localStorage.getItem('smResult')||'{"main":1,"sub":7}')}
function matched(j){let r=res();return j.types.includes(r.main)||j.types.includes(r.sub)}
function nav(active='recommend'){return `<nav class="bottom">${[['recommend','⌂','オススメ'],['search','⌕','探す'],['likes','👀','キニナル'],['mypage','●','マイページ']].map(x=>`<button class="${active==x[0]?'on':''}" onclick="go('${x[0]}')"><b>${x[1]}</b><span>${x[2]}</span></button>`).join('')}</nav>`}
function page(body,active='',right='<button class="bell">🔔</button>'){app.innerHTML=shell(header(right)+body+(active?nav(active):''));window.scrollTo(0,0)}
window.go=id=>{({recommend,search,likes,mypage,history,scouts,applications,employer:employerHome}[id]||home)()};
function jobCard(j,full=false){return `<article class="job tappable" onclick="detail(${j.id})"><div class="jobphoto">${j.icon}<span>${j.cat}</span></div><div class="jobbody">${matched(j)?'<span class="match">✨アナタと相性抜群！</span>':''}${state.scouts.includes(j.id)?'<span class="scouttag">✨スカウト</span>':''}<h3>${j.name}</h3><div class="meta">📍 ${j.station}<br>💴 時給${j.wage.toLocaleString()}円〜　・　${j.role}</div><div class="tags">${j.tags.slice(0,2).map(t=>`<span>${t}</span>`).join('')}</div></div>${full?`<div class="actions"><button onclick="event.stopPropagation();pass(${j.id})">見送る🙏</button><button class="orange" onclick="event.stopPropagation();like(${j.id})">👀キニナル</button></div>`:''}</article>`}
window.jobs=(m,s)=>recommend(true);function recommend(guest=false){let list=[...stores].sort((a,b)=>(state.scouts.includes(b.id)-state.scouts.includes(a.id))+(matched(b)-matched(a))).filter(j=>!state.passed.includes(j.id)); if(guest)list=list.slice(0,3);page(`<main class="jobs"><div class="eyebrow">FOR YOU</div><h1>${guest?'あなたに合うお店':'今日のオススメ'}</h1><p class="small">${guest?'まずはおすすめの3店舗をチェック。':'カードを見て、気になるお店を保存しよう。'}</p>${list.map(j=>jobCard(j,!guest)).join('')}${guest?`<section class="gate"><h2>もっとお店を見る？</h2><p>無料会員登録すると、求人をもっと見たり<br>👀キニナルに保存できます。</p><button class="btn primary" onclick="register()">無料で会員登録</button><button class="btn secondary" onclick="login()">ログイン</button></section>`:''}</main>`,guest?'':'recommend')}
window.like=id=>{if(!state.liked.includes(id))state.liked.push(id);state.passed=state.passed.filter(x=>x!==id);save();toast('👀 キニナルに保存しました')};window.pass=id=>{state.passed.push(id);state.liked=state.liked.filter(x=>x!==id);save();recommend()};
function search(){page(`<main class="jobs"><div class="eyebrow">SEARCH</div><h1>お店を探す</h1><div class="searchbar"><input id="q" placeholder="駅名・店名・業態" oninput="filterJobs()"><button onclick="filters()">条件</button></div><div class="filterchips"><span>勤務地</span><span>最低時給</span><span>業態</span><span>職種</span><span>勤務時間</span></div><div id="searchResults">${stores.map(j=>jobCard(j)).join('')}</div></main>`,'search')}
window.filterJobs=()=>{let q=document.getElementById('q').value.toLowerCase();let a=stores.filter(j=>(j.name+j.cat+j.station+j.role).toLowerCase().includes(q));document.getElementById('searchResults').innerHTML=a.length?a.map(jobCard).join(''):`<section class="empty"><h3>条件にぴったりのお店は見つかりませんでした🥲</h3><p>でも、条件が近いお店があります！<br>少し条件を広げて探してみました 🔍</p></section>${stores.slice(0,2).map(jobCard).join('')}`};window.filters=()=>toast('詳細フィルターUIは実装済み想定のデモです');
function likes(){let a=stores.filter(j=>state.liked.includes(j.id));page(`<main class="jobs"><h1>👀キニナル</h1><p class="small">${state.user?'保存したお店を比較できます。':'無料登録では3件まで保存できます。'}</p>${a.length?a.map(jobCard).join(''):'<section class="empty">まだキニナルしたお店はありません。</section>'}</main>`,'likes')}
window.detail=id=>{let j=stores.find(x=>x.id==id);page(`<main class="detail"><div class="detailhero">${j.icon}</div>${state.scouts.includes(id)?'<div class="scoutbox">✨このお店からスカウトが届いています</div>':''}<section class="first">${matched(j)?'<span class="match">✨アナタと相性抜群！</span>':''}<h1>${j.name}</h1><p>${j.cat} ・ ${j.station}</p><div class="tags">${j.tags.map(t=>`<span>${t}</span>`).join('')}</div></section><section><h2>募集条件</h2><div class="spec"><b>給与</b><span>時給${j.wage.toLocaleString()}円〜</span><b>職種</b><span>${j.role}</span><b>勤務時間</b><span>${j.hours}</span><b>最低シフト</b><span>${j.shift}</span></div></section><section><h2>仕事内容</h2><p>${j.role}業務を中心に、店舗運営に必要な仕事をチームで担当します。</p></section><section><h2>お店について</h2><p>${j.copy}</p></section><section><h2>待遇・身だしなみ</h2><div class="tags">${j.benefits.map(t=>`<span>${t}</span>`).join('')}</div></section>${matched(j)?`<section class="reason"><h2>あなたに合う理由</h2><p>このお店が求めている「${j.types.filter(t=>[res().main,res().sub].includes(t)).map(t=>types[t].name).join('」と「')}」と、あなたの診断結果がマッチしています。</p></section>`:''}<section><h2>勤務地・アクセス</h2><p>${j.station}<br>通勤方法：電車・バス・自転車</p></section><div class="sticky"><button onclick="like(${j.id})">👀キニナル</button><button class="orange" onclick="apply(${j.id})">応募する</button></div></main>`)};
window.apply=id=>{if(!state.user){register(id);return}let j=stores.find(x=>x.id==id);page(`<main class="form"><div class="eyebrow">APPLICATION</div><h1>${j.name}に応募</h1><p class="small">応募内容から履歴書を自動作成します。</p>${['本名','フリガナ','生年月日','電話番号','住所','最寄り駅'].map((x,i)=>`<label>${x}<input id="a${i}" placeholder="${x}"></label>`).join('')}<label>現在の職<select><option>アルバイト</option><option>学生</option><option>正社員</option><option>その他</option></select></label><button class="btn primary" onclick="resume(${id})">作成される履歴書を見る</button></main>`)};
window.resume=id=>{let j=stores.find(x=>x.id==id),r=res();page(`<main class="resume"><div class="resumehead"><small>Shoku↔match 履歴書</small><h1>応募用履歴書プレビュー</h1></div><div class="paper"><h2>${j.name} 応募</h2><p><b>氏名</b>　田中 理子（入力内容のデモ）</p><p><b>最寄り駅</b>　登録情報から反映</p><p><b>飲食経験</b>　プロフィールから反映</p><p><b>仕事タイプ</b>　${types[r.main].name}<br>SUB：${types[r.sub].name}</p><p><b>資格・スキル</b>　プロフィールから反映</p><p class="small">※実際には入力・登録された情報だけを使用し、AIが内容を作り足すことはありません。</p></div><button class="btn primary" onclick="sendApply(${id})">この内容で応募する</button><button class="btn secondary" onclick="apply(${id})">修正する</button></main>`)};window.sendApply=id=>{if(!state.apps.includes(id))state.apps.push(id);save();toast('応募を送信しました！');applications()};
function applications(){page(`<main class="jobs"><h1>応募・選考状況</h1>${state.apps.length?state.apps.map((id,i)=>{let j=stores.find(x=>x.id==id);return `<article class="statuscard"><b>${j.name}</b><span>${i?'面接予定':'面接日程調整中'}</span><div class="timeline">応募済み → 面接日程調整中 → 面接予定 → 選考中 → 選考完了</div>${i?'<button class="btn secondary" onclick="toast(\'面接：10/8 18:30\')">面接詳細</button>':'<button class="btn primary" onclick="schedule('+id+')">面接候補日を選ぶ</button>'}</article>`}).join(''):'<section class="empty">応募中の求人はありません。</section>'}</main>`,'mypage')}
window.schedule=id=>page(`<main class="form"><h1>面接日時を選択</h1><p>店舗から届いた候補から選んでください。</p>${['10/8 18:30','10/9 17:00','10/11 15:30'].map(x=>`<button class="choice" onclick="toast('面接日時を確定しました：${x}');applications()">${x}</button>`).join('')}<section><h2>面接場所</h2><p>店舗 / 担当：採用担当者<br>当日連絡先：店舗電話番号</p></section></main>`);
function history(){page(`<main class="jobs"><h1>見送り履歴</h1><p class="small">あとから👀キニナルに変更できます。</p>${stores.filter(j=>state.passed.includes(j.id)).map(j=>jobCard(j)).join('')||'<section class="empty">見送り履歴はありません。</section>'}</main>`,'mypage')}
function scouts(){page(`<main class="jobs"><h1>スカウト履歴</h1>${stores.filter(j=>state.scouts.includes(j.id)).map(j=>`<div class="scoutbox">✨スカウトが届きました！</div>${jobCard(j)}`).join('')}</main>`,'mypage')}
function mypage(){let r=res();page(`<main class="mypage"><section class="profiletop"><img src="${A+types[r.main].img}"><div><small>MAIN TYPE</small><h2>${state.user?.name||'ゲストユーザー'}</h2><p>${types[r.main].name}</p></div></section><div class="completion"><b>プロフィール完成度 65%</b><div><i style="width:65%"></i></div><p>プロフィールを完成すると👀キニナルが無制限になります。</p></div><div class="menulist"><button onclick="applications()">応募・選考状況 <span>›</span></button><button onclick="scouts()">スカウト履歴 <span>›</span></button><button onclick="history()">見送り履歴 <span>›</span></button><button onclick="result(${r.main},${r.sub})">仕事タイプ診断結果 <span>›</span></button><button onclick="profileEdit()">プロフィール編集 <span>›</span></button><button onclick="employerHome()">企業側デモを見る <span>›</span></button></div></main>`,'mypage')}
window.profileEdit=()=>page(`<main class="form"><h1>プロフィール編集</h1>${['ユーザー名','年齢','性別','最終学歴','国籍','飲食経験の詳細','資格・スキル','自己PR','希望エリア・駅','希望勤務時間帯','希望勤務日数'].map(x=>`<label>${x}<input placeholder="${x}"></label>`).join('')}<button class="btn primary" onclick="toast('プロフィールを保存しました');mypage()">保存する</button></main>`);
window.register=(after)=>auth(false,after);window.login=()=>auth(true);function auth(login,after){page(`<main class="auth"><div class="eyebrow">${login?'WELCOME BACK':'FREE ACCOUNT'}</div><h1>${login?'おかえりなさい':'続きを見よう'}</h1><div class="field"><label>メールアドレス</label><input id="email" type="email" placeholder="example@email.com"></div><div class="field"><label>パスワード</label><input id="pw" type="password" placeholder="8文字以上"></div>${login?'':`<div class="field"><label>ユーザー名</label><input id="uname" placeholder="例：りこ"></div><div class="field"><label>年齢</label><input type="number" placeholder="例：27"></div><div class="field"><label>飲食経験</label><select><option>未経験</option><option>1年未満</option><option>1〜3年</option><option>3年以上</option></select></div><div class="field"><label>現在の仕事状況</label><select><option>学生</option><option>アルバイト</option><option>正社員</option><option>フリーター</option><option>その他</option></select></div>`}<button class="btn primary" onclick="demoAuth(${after||0})">${login?'ログイン':'メールアドレスを確認して登録'}</button><p class="loginlink">※現在はプロトタイプのため、認証情報は端末内だけに保存されます。本番ではメール認証・安全なバックエンドへ接続します。</p></main>`)}
window.demoAuth=after=>{state.user={name:document.getElementById('uname')?.value||'りこ'};save();after?apply(after):recommend()};
function employerHome(){state.employer=true;page(`<main class="emp"><div class="empbrand">FOR EMPLOYERS</div><h1>企業ダッシュボード</h1><div class="stats"><article><b>4</b><span>新着応募</span></article><article><b>2</b><span>日程調整</span></article><article><b>1</b><span>本日の面接</span></article><article><b>3/5</b><span>スカウト残</span></article></div><div class="alert">⚠️ 選考結果の入力待ちが1件あります</div><div class="menulist"><button onclick="jobManage()">店舗・求人管理 <span>›</span></button><button onclick="applicantManage()">応募者管理 <span>›</span></button><button onclick="talent()">人材を探す <span>›</span></button><button onclick="scoutManage()">スカウト管理 <span>›</span></button><button onclick="pricing()">契約・料金 <span>›</span></button><button onclick="home()">ユーザー側に戻る <span>›</span></button></div></main>`)}
window.jobManage=()=>page(`<main class="emp"><h1>店舗・求人管理</h1><button class="btn primary" onclick="jobCreate()">＋ 新しい求人を作成</button>${stores.slice(0,3).map(j=>`<article class="manage"><div><b>${j.name}</b><p>${j.role} / 時給${j.wage}円〜</p></div><span class="live">公開中</span></article>`).join('')}</main>`);
window.jobCreate=()=>page(`<main class="form"><div class="eyebrow">STEP 1–5</div><h1>求人を作成</h1>${['店舗','業態','職種（複数可）','仕事内容','推しポイント①','推しポイント②','給与','研修時給・条件','勤務時間','最低シフト','通勤方法','お店からひとこと','求める仕事タイプ（1〜3）'].map(x=>`<label>${x}<input placeholder="${x}"></label>`).join('')}<section><h2>写真</h2><p>3〜8枚。制服写真がおすすめです。</p><div class="upload">＋ 写真を追加</div></section><button class="btn primary" onclick="toast('求人を下書き保存しました');jobManage()">確認・下書き保存</button></main>`);
window.applicantManage=()=>page(`<main class="emp"><h1>応募者管理</h1>${[1,2,3].map((n,i)=>{let t=[2,5,7][i];return `<article class="applicant"><img src="${A+types[t].img}"><div><b>${['mii','haru','sora'][i]}</b><p>${[22,27,19][i]}歳 / 飲食経験 ${['2年','5年','未経験'][i]}</p><span>${types[t].name}</span></div><button onclick="applicant(${i})">詳細</button></article>`}).join('')}</main>`);
window.applicant=i=>page(`<main class="emp"><h1>応募者詳細</h1><section class="paper"><h2>${['mii','haru','sora'][i]}</h2><p>MAIN / SUBタイプ、飲食経験、学歴、資格・スキル、自己PR、応募時の個人情報を確認できます。</p><p><b>累計無断欠席：</b>0回</p></section><div class="split"><button class="btn secondary" onclick="toast('見送りとして記録しました')">見送る</button><button class="btn primary" onclick="toast('面接候補日の作成へ進みます')">面接へ進める</button></div></main>`);
window.talent=()=>page(`<main class="emp"><h1>人材を探す</h1><div class="searchbar"><input placeholder="MAINタイプ・エリア・経験など"><button>検索</button></div>${[1,3,8].map((t,i)=>`<article class="applicant"><img src="${A+types[t].img}"><div><b>${['aki','nana','yuu'][i]}</b><p>${[24,20,29][i]}歳 / 希望：都内</p><span>${types[t].name}</span></div><button onclick="toast('店舗・求人を選んでスカウトを送信できます')">スカウト</button></article>`).join('')}</main>`);
window.scoutManage=()=>page(`<main class="emp"><h1>スカウト管理</h1><div class="quota"><b>今月 2 / 5通 使用</b><div><i style="width:40%"></i></div><p>残り3通</p></div><section><h2>テンプレート</h2><article class="manage"><div><b>ホール経験者向け</b><p>ぜひ一度お話ししませんか？</p></div><button>編集</button></article></section><section><h2>反応</h2><p>👀キニナル 1件　・　応募 1件</p></section></main>`);
window.pricing=()=>page(`<main class="emp"><h1>契約・料金</h1><section class="paper"><h2>現在のプラン</h2><p>1店舗プラン　月額〇円</p><p>スカウト：標準5通/月</p></section><section class="paper"><h2>スカウト追加</h2><p>10通 +¥3,000<br>20通 +¥5,000<br>無制限 +¥20,000</p></section></main>`);
function toast(msg){let d=document.createElement('div');d.className='toast';d.textContent=msg;document.body.appendChild(d);setTimeout(()=>d.remove(),1800)}
window.toast=toast;
home();
